### ISSUE TITLE
Create a schema for Weaviate 

### ISSUE THREAD

**Issue by chrisammon3000** [chrisammon3000/aws-open-data-registry-neural-search#2]
## Description
Create a schema for Weaviate to describe the AWS Open Registry datasets.

### Tasks
- [x] Create a schema JSON file and initialize database from the user data using curl
- [x] Upload to S3 on stack deployment
- [x] Download to instance during bootstrapping

## Resources
[How to create a schema?](https://weaviate.io/developers/weaviate/current/tutorials/how-to-create-a-schema.html)
